name: release
on:
  push:
    tags:
      - 'v*'

env:
  BUILD_ENV: release

jobs:
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    steps:
      - name: get version number
        run: |
          echo "GITHUB_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: print version number
        run: |
          echo "tag = ${{ env.GITHUB_TAG }}"

      - name: create release on github
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.GITHUB_TAG }}
          release_name: v${{ env.GITHUB_TAG }}

      - name: generate env artifact
        run: |
          echo "RELEASE_UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" > artifact-env
          echo "GITHUB_TAG=$GITHUB_TAG" >> artifact-env

      - name: save env artifact
        uses: actions/upload-artifact@v1
        with:
          name: artifact-env
          path: artifact-env

  build-node-files:
    name: build-node-files
    needs: ['create-release']
    runs-on: ${{ matrix.build.os }}
    env:
      BUILD_ENV: release
    strategy:
      fail-fast: false
      matrix:
        build:
          - { os: ubuntu-latest, output: linux-x86_64.node }
          - { os: macos-latest, output: darwin-x86_64.node }
    steps:
      - name: set NPM_CONFIG_PREFIX
        run: |
          echo "NPM_CONFIG_PREFIX=$HOME/.npm-global" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v2

      - name: download env artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact-env
          path: artifact-env

      - name: load env artifact
        run: cat artifact-env/artifact-env >> $GITHUB_ENV

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: configure NPM_CONFIG_PREFIX
        run: |
          npm config set prefix $NPM_CONFIG_PREFIX
          mkdir -p $NPM_CONFIG_PREFIX/bin
          mkdir -p $NPM_CONFIG_PREFIX/lib
          echo "$NPM_CONFIG_PREFIX/bin" >> $GITHUB_PATH

      - name: install node-gyp
        run: |
          npm install -g node-gyp
          echo $PATH
          which node-gyp

      - name: npm install
        run: npm install --ignore-scripts

      - name: configure
        run: |
          make update-cpp-bindings
          make generate-bindings
          make configure

      - name: build
        run: make build

      - name: run tests
        run: make test

      - name: upload assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: build/Release/ruby_parser.node
          asset_name: ${{ matrix.build.output }}
          asset_content_type: application/octet-stream

      - name: save .node file as artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.build.output }}
          path: build/Release/ruby_parser.node

  build-package:
    name: build-package
    needs: ['build-node-files']
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'

      - name: download linux artifact
        uses: actions/download-artifact@v1
        with:
          name: linux-x86_64.node
          path: linux-x86_64.node

      - name: download macos artifact
        uses: actions/download-artifact@v1
        with:
          name: darwin-x86_64.node
          path: darwin-x86_64.node

      - name: download env artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact-env
          path: artifact-env

      - name: load env artifact
        run: cat artifact-env/artifact-env >> $GITHUB_ENV

      - name: build package
        run: |
          ls -l linux-x86_64.node/
          ls -l darwin-x86_64.node/

          cp linux-x86_64.node/ruby_parser.node pkg/linux-x86_64.node
          cp darwin-x86_64.node/ruby_parser.node pkg/darwin-x86_64.node
          cp LICENSE pkg/
          cp README.md pkg/
          cd pkg

          npm version "$GITHUB_TAG" --no-git-tag-version
          npm pack
          ls -l

      - name: upload assets
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.RELEASE_UPLOAD_URL }}
          asset_path: pkg/lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz
          asset_name: lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz
          asset_content_type: application/octet-stream

      - name: save .tgz package as artifact
        uses: actions/upload-artifact@v1
        with:
          name: lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz
          path: pkg/lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz

  test-package:
    name: test-package
    needs: ['build-package']
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [ '10', '12', '14', '15' ]
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: download env artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact-env
          path: artifact-env

      - name: load env artifact
        run: cat artifact-env/artifact-env >> $GITHUB_ENV

      - name: download .tgz artifact
        uses: actions/download-artifact@v1
        with:
          name: lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz
          path: lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz

      - name: test
        run: |
          mkdir test
          cd test
          echo "{}" > package.json
          npm install ../lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz/lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz

          node -e "console.log(require.resolve('lib-ruby-parser'))"
          node -e "console.log(require('lib-ruby-parser').parse('2 + 2', {}))"

  publish-package:
    name: publish-package
    needs: ['test-package']
    runs-on: ubuntu-latest
    steps:
      - name: download env artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact-env
          path: artifact-env

      - name: load env artifact
        run: cat artifact-env/artifact-env >> $GITHUB_ENV

      - name: download .tgz artifact
        uses: actions/download-artifact@v1
        with:
          name: lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz
          path: lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: 'https://registry.npmjs.org'

      - name: publish
        run: npm publish $PWD/lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz/lib-ruby-parser-${{ env.GITHUB_TAG }}.tgz
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
