name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  BUILD_ENV: release

defaults:
  run:
    shell: bash

jobs:
  test:
    name: run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node: [ '12', '14', '16', '17', '18' ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    steps:
      - name: install wget
        if: runner.os == 'Windows'
        run: choco install wget --no-progress

      - name: checkout
        uses: actions/checkout@v2

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: build
        run: |
          make setup
          make download-cpp-bindings
          make do-codegen

          make configure
          make build

      - name: Run tests
        run: make test
