name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '12', '14' ]

    steps:
      - name: set NPM_CONFIG_PREFIX
        run: |
          echo "NPM_CONFIG_PREFIX=$HOME/.npm-global" >> $GITHUB_ENV

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install node
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}

      - name: configure NPM_CONFIG_PREFIX
        run: |
          npm config set prefix $NPM_CONFIG_PREFIX
          echo "$NPM_CONFIG_PREFIX/bin" >> $GITHUB_PATH

      - name: install node-gyp
        run: |
          npm install -g node-gyp
          echo $PATH
          which node-gyp

      - name: npm install
        run: npm install

      - name: Run tests
        run: make test-debug
